name: build

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/cache@v4
      with:
        key: env-files-win
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: .\setup.bat
    - run: .\build.bat -p Windows
    - uses: actions/upload-artifact@v4
      with:
        name: Windows
        path: ./build/Windows
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/cache@v4
      with:
        key: env-files-linux
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: ./setup.sh
    - run: ./build.sh -p Android
    - uses: actions/upload-artifact@v4
      with:
        name: Android
        path: ./build/Android
  ios:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        key: env-files-linux
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: ./setup.sh
    - run: ./build.sh -p iOS
    - uses: actions/upload-artifact@v4
      with:
        name: iOS
        path: ./build/iOS
